# Generated by Django 2.2.1 on 2019-07-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=80)),
                ('species', models.CharField(max_length=80)),
                ('unit', models.CharField(choices=[('couple', 'couple'), ('male', 'male'), ('female', 'female'), ('none', 'none')], default='none', max_length=10)),
                ('price', models.IntegerField()),
                ('publication_date', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
        ),
    ]
