# Generated by Django 2.2.1 on 2019-07-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitprice',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unitprice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
