# Generated by Django 2.2.1 on 2019-07-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20190718_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitprice',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
