# Generated by Django 2.2.1 on 2019-07-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20190718_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitprice',
            old_name='classification',
            new_name='breed',
        ),
    ]
