# Generated by Django 2.2.1 on 2019-07-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_auto_20190719_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitprice',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='unitprice',
            name='species',
        ),
    ]
