# Generated by Django 2.2.1 on 2019-07-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_auto_20190719_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitprice',
            name='breed',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitprice',
            name='species',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
