# Generated by Django 2.2.1 on 2019-08-30 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('section_color', models.CharField(max_length=20)),
                ('aquarium_num_of_rows', models.IntegerField(default=0)),
                ('aquarium_num_of_columns', models.IntegerField(default=0)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StorageRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_room_name', models.CharField(max_length=100)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('aquarium_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.AquariumSection')),
                ('storage_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StorageRoom')),
            ],
        ),
        migrations.AddField(
            model_name='aquariumsection',
            name='storage_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StorageRoom'),
        ),
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('operation_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('memo', models.TextField(blank=True, null=True)),
                ('setup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('aquarium_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.AquariumSection')),
            ],
        ),
    ]
