# Generated by Django 2.2.1 on 2019-06-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=20)),
                ('section_color', models.CharField(max_length=20)),
                ('aquarium_num_of_rows', models.IntegerField(default=0)),
                ('aquarium_num_of_columns', models.IntegerField(default=0)),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_room_name', models.CharField(max_length=20)),
                ('modified_date', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLayout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('aquarium_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.AquariumSection')),
                ('storage_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StorageRoom')),
            ],
        ),
        migrations.AddField(
            model_name='aquariumsection',
            name='storage_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StorageRoom'),
        ),
    ]
