# Generated by Django 2.2.1 on 2019-07-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_business_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
                ('section_color', models.CharField(max_length=20)),
                ('aquarium_num_of_rows', models.IntegerField(default=0)),
                ('aquarium_num_of_columns', models.IntegerField(default=0)),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_room_name', models.CharField(max_length=20)),
                ('modified_date', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('aquarium_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.AquariumSection')),
                ('storage_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StorageRoom')),
            ],
        ),
        migrations.AddField(
            model_name='aquariumsection',
            name='storage_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StorageRoom'),
        ),
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('alias', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('memo', models.TextField()),
                ('ph', models.FloatField(default=7.0)),
                ('config_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('aquarium_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.AquariumSection')),
            ],
        ),
    ]
