# Generated by Django 2.2.1 on 2019-07-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('alias', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('memo', models.TextField()),
                ('ph', models.FloatField(default=7.0)),
                ('config_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('aquarium_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.AquariumSection')),
            ],
        ),
    ]
