# Generated by Django 2.2.1 on 2019-08-30 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
            ],
        ),
    ]
