# Generated by Django 2.2.1 on 2019-08-30 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_size', models.FloatField(default=0.0)),
                ('max_size', models.FloatField(default=0.0)),
                ('stages_of_development', models.CharField(choices=[('adult', 'adult'), ('immature', 'immature'), ('juvenile', 'juvenile'), ('larva', 'larva')], default='adult', max_length=20)),
                ('unit', models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male')], default='none', max_length=20)),
                ('scope_of_sales', models.CharField(choices=[('store_and_online', 'store_and_online'), ('store_only', 'store_only'), ('online_only', 'online_only'), ('not_for_sale', 'not_for_sale')], default='not_for_sale', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('order_quantity', models.IntegerField(default=0)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Creature')),
            ],
        ),
    ]
