# Generated by Django 2.2.1 on 2019-08-10 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_size', models.FloatField(default=0.0)),
                ('max_size', models.FloatField(default=0.0)),
                ('stages_of_development', models.CharField(choices=[('adult', 'adult'), ('immature', 'immature'), ('juvenile', 'juvenile'), ('larva', 'larva')], default='adult', max_length=20)),
                ('unit', models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male')], default='none', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
                ('creature_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CreatureItem')),
            ],
        ),
    ]
