# Generated by Django 2.2.1 on 2019-08-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190815_1325'),
        ('console', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatureItem',
            new_name='Creature',
        ),
        migrations.RenameField(
            model_name='unitprice',
            old_name='creature_item',
            new_name='creature',
        ),
    ]
