# Generated by Django 2.2.1 on 2019-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_unitprice_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitprice',
            name='scope_of_sales',
            field=models.CharField(choices=[('not_for_sale', 'not_for_sale'), ('delivery_and_pickup', 'delivery_and_pickup'), ('pickup_only', 'pickup_only'), ('delivery_only', 'delivery_only')], default='not_for_sale', max_length=20),
        ),
    ]
