# Generated by Django 2.2.1 on 2019-08-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_unitprice_scope_of_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitprice',
            name='scope_of_sales',
            field=models.CharField(choices=[('delivery_and_pickup', 'delivery_and_pickup'), ('pickup_only', 'pickup_only'), ('delivery_only', 'delivery_only'), ('not_for_sale', 'not_for_sale')], default='not_for_sale', max_length=20),
        ),
    ]
