# Generated by Django 2.2.1 on 2019-08-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190817_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
