# Generated by Django 2.2.1 on 2019-08-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_creature_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitprice',
            name='scope_of_sales',
            field=models.CharField(choices=[('offline_and_online', 'offline_and_online'), ('offline_only', 'offline_only'), ('online_only', 'online_only'), ('not_for_sale', 'not_for_sale')], default='not_for_sale', max_length=20),
        ),
    ]
