# Generated by Django 2.2.1 on 2019-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sales_status',
            field=models.CharField(choices=[('not_for_sale', 'not_for_sale'), ('on_sale', 'on_sale'), ('sold_out', 'sold_out')], default='not_for_sale', max_length=20),
        ),
    ]
