# Generated by Django 2.2.1 on 2019-08-30 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('store', '0001_initial'),
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male')], default='none', max_length=20)),
                ('size', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Aquarium')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Creature')),
                ('unit_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.UnitPrice')),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('goods_issue', 'goods_issue'), ('goods_receipt', 'goods_receipt')], default='goods_issue', max_length=20)),
                ('description', models.CharField(choices=[('goods_sales', 'goods_sales'), ('parcel_out', 'parcel_out'), ('death', 'death'), ('purchase_of_goods', 'purchase_of_goods'), ('adoption', 'adoption')], default='goods_sales', max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_price', models.IntegerField(blank=True, null=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Aquarium')),
                ('aquarium_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.AquariumStock')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
            ],
        ),
    ]
