# Generated by Django 2.2.1 on 2019-08-11 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_auto_20190811_1120'),
        ('console', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquariumStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('remark', models.TextField(blank=True, null=True)),
                ('price_change', models.IntegerField(default=0)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Aquarium')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
                ('creature_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CreatureItem')),
            ],
        ),
    ]
