# Generated by Django 2.2.1 on 2019-08-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquariumstock',
            name='price_change',
        ),
    ]
