# Generated by Django 2.2.1 on 2019-08-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_aquariumstock_price_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquariumstock',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
