# Generated by Django 2.2.1 on 2019-08-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190811_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aquariumstock',
            old_name='creature_item',
            new_name='creature',
        ),
    ]
