# Generated by Django 2.2.1 on 2019-08-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_aquariumstock_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquariumstock',
            name='gender',
            field=models.CharField(choices=[('none', 'none'), ('female', 'female'), ('male', 'male')], default='none', max_length=20),
        ),
    ]
