# Generated by Django 2.2.1 on 2019-08-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_aquariumstock_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquariumstock',
            name='remark',
        ),
    ]
