# Generated by Django 2.2.1 on 2019-08-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
        ('order', '0006_auto_20190823_1100'),
        ('store', '0002_auto_20190811_1120'),
        ('inventory', '0007_remove_aquariumstock_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(choices=[('with_shipping_closing', 'with_shipping_closing'), ('without_shipping_closing', 'without_shipping_closing'), ('with_receiving_closing', 'with_receiving_closing'), ('without_receiving_closing', 'without_receiving_closing')], default='with_shipping_closing', max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('with_receiving_closing_price', models.IntegerField(blank=True, default=0, null=True)),
                ('without_shipping_closing_type', models.CharField(choices=[('parcel_out', 'parcel_out'), ('death', 'death')], default='parcel_out', max_length=20)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Aquarium')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
            ],
        ),
    ]
