# Generated by Django 2.2.1 on 2019-08-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='without_shipping_closing_type',
            field=models.CharField(choices=[(None, None), ('parcel_out', 'parcel_out'), ('death', 'death')], default=None, max_length=20),
        ),
    ]
