# Generated by Django 2.2.1 on 2019-08-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190827_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='with_receiving_closing_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
