# Generated by Django 2.2.1 on 2019-08-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190823_1100'),
        ('store', '0002_auto_20190811_1120'),
        ('console', '0001_initial'),
        ('inventory', '0011_auto_20190827_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('goods_issue', 'goods_issue'), ('goods_receipt', 'goods_receipt')], default='goods_issue', max_length=20)),
                ('description', models.CharField(choices=[('goods_sales', 'goods_sales'), ('parcel_out', 'parcel_out'), ('death', 'death'), ('purchase_of_goods', 'purchase_of_goods'), ('adoption', 'adoption')], default='goods_sales', max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_price', models.IntegerField(blank=True, null=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Aquarium')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderItem')),
            ],
        ),
        migrations.DeleteModel(
            name='StockRecord',
        ),
    ]
