# Generated by Django 2.2.1 on 2019-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20190810_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='alias',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
