# Generated by Django 2.2.1 on 2019-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_type',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('pickup', 'pickup'), ('delivery', 'delivery')], default='pickup', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('active', 'active'), ('canceled', 'canceled')], default='active', max_length=20),
        ),
    ]
