# Generated by Django 2.2.1 on 2019-08-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190819_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
